---

- name: APTLY | Installing dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ required_libs }}"
  tags:
    skip_ansible_lint

- name: APTLY | Ensure aptly group
  group:
    name: "{{ aptly_group }}"

- name: APTLY | Ensure aptly user
  user:
    name: "{{ aptly_user }}"
    group: "{{ aptly_group }}"
    shell: /bin/bash

- name: APTLY | Copy Daemon script
  template:
    src: aptly.service.j2
    dest: /lib/systemd/system/aptly.service
    mode: 0644
  notify: restart aptly

- name: APTLY | Copy Daemon script (API)
  template:
    src: aptly-api.service.j2
    dest: /lib/systemd/system/aptly-api.service
    mode: 0644
  notify: restart aptly-api

- name: APTLY | Copy aptly-upload script
  template:
    src: aptly-upload
    dest: /usr/bin/aptly-upload
    mode: 0555
